blogw/blogw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('blogwapp/', include('blogwapp.urls')),
    path('admin/', admin.site.urls),
    path('projectapi/',include('projectapi.urls'))
    ,path('accounts/',include('django.contrib.auth.urls'))
]

blogw/blogwapp/urls.py
from django.urls import path
from rest_framework import routers
from . import views

app_name = 'blogwapp'

# rest framework
#router = routers.DefaultRouter()
#router.register(r'users', views.UserViewSet)

urlpatterns = [
  # /blogwapp/ => index, pag. Principal, lista de proyectos (GET)
  #path('', views.IndexView.as_view(), name='index'),
  path('',views.ProjectListView.as_view(),name='project-list') ,

  # blogwapp/ID/  => detalle del proyecto  (GET AJAX)
  path('<int:pk>/', views.ProjectDetailView.as_view(), name='project-detail'),

  # blogwapp/ID/blogs  => lista de blogs del proyecto (GET AJAX)
  path('<int:pk>/blogs/', views.BlogListView.as_view(), name='blog-list'),

  # blogwapp/add  => crear proyecto (GET, POST AJAX)
  path('create/', views.ProjectCreateView.as_view(), name='project-add'),

  # blogwapp/ID/update => update proyecto (GET , POST)
  path('<int:pk>/update/', views.ProjectUpdateView.as_view(), name='project-update'),

  # blogwapp/ID/delete => delete proyecto (POST AJAX)
  path('<int:pk>/delete/', views.ProjectDeleteView.as_view(), name='project-delete'),

  # blogwapp/blog/ID => detalle blog 
  path('blog/<int:pk>/', views.BlogDetailView.as_view(), name='blog-detail'),

  # blogwapp/PROJ_ID/blog/create  => crear blog
  path('<int:pk>/create/', views.BlogCreateView.as_view(), name='blog-add'),

  # blogwapp/ID/blog/update  => update blog
  path('blog/<int:pk>/update/', views.BlogUpdateView.as_view(), name='blog-update'),

  # blogwapp/blog/ID/delete => update blog
  path('blog/<int:pk>/delete/', views.BlogDeleteView.as_view(), name='blog-delete'),
]

blogw/projectapi/urls.py
from django.urls import include, path
from rest_framework import routers
#from tutorial.quickstart import views
from . import views

app_name = 'projectapi'

router = routers.DefaultRouter()
router.register(r'projects', views.ProjectViewSet)
router.register(r'blogs', views.BlogViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

blogw/blogwapp/models.py
import datetime 
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.

class Project(models.Model):
  name = models.CharField(max_length=200, null=False)
  title = models.CharField(max_length=200)
  creat_date= models.DateTimeField('date created', default=timezone.now)
  description = models.CharField(max_length=2000, null=False)
  update_date = models.DateTimeField('date updated',auto_now=True)

  def __str__(self):
    return self.name

  def was_published_recently(self):
    return self.creat_date >= timezone.now() - datetime.timedelta(days=1)  

  @property
  def last_blog(self):
    return self.blogs.last()  

  def get_absolute_url(self):
    return reverse('blogwapp:project-detail', kwargs={'pk': self.pk})  

class Blog(models.Model):
  project = models.ForeignKey(Project, related_name='blogs',on_delete=models.CASCADE)
  creat_date = models.DateTimeField('date created', default=timezone.now)
  text = models.CharField(max_length=200, null=False)
  update_date = models.DateTimeField('date updated', auto_now=True)

  def __str__(self):
    return self.text

  def last_blog(self):
    return self.pub_date >= timezone.now() - datetime.timedelta(days=1)  

  def get_absolute_url(self):
    return reverse('blogwapp:blog-detail', kwargs={'pk': self.pk}) 

blogw/blogwapp/views.py
from django.http import HttpResponse
from .models import Blog,Project
from django.template import loader 
from django.http import HttpResponseRedirect,JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.views.generic import TemplateView,View,ListView,CreateView,UpdateView,DeleteView
from django.db.models import Count,Max
from django.core import serializers
from json import dumps 
from django.contrib.auth.mixins import LoginRequiredMixin

class ProjectListView(LoginRequiredMixin, ListView):
    redirect_field_name = 'redirect_to'
    template_name = 'blogwapp/project/list.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Project.objects.annotate(num_blogs=Count('blogs')).annotate(max_date=Max('blogs__creat_date'))

class ProjectDetailView(generic.DetailView, LoginRequiredMixin):
  model = Project
  template_name = 'blogwapp/project/detail.html'
  queryset = Project.objects.annotate(blog_count=Count('blogs')).all()


class ProjectCreateView(CreateView, LoginRequiredMixin):
  model = Project
  fields = ['name','description']
  template_name = 'blogwapp/project/create.html'

class ProjectUpdateView(UpdateView, LoginRequiredMixin):
  model = Project
  fields = ['name','description']
  template_name = 'blogwapp/project/update.html'

class ProjectDeleteView(DeleteView, LoginRequiredMixin):
  pass 

class BlogListView(generic.ListView, LoginRequiredMixin):
  template_name = 'blogwapp/blog/list.html'
  context_object_name = 'latest_question_list'

  def get_queryset(self):
    pk = self.kwargs.get('pk')
    return Blog.objects.filter(project__id=pk).all()

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['project_id'] = self.kwargs.get('pk')
    return context  

class BlogDetailView(generic.DetailView):
  model = Blog
  template_name = 'blogwapp/blog/detail.html'
  #queryset = Blog.objects.annotate(blog_count=Count('blogs')).all()

class BlogCreateView(CreateView,LoginRequiredMixin):
  model = Blog
  fields = ['text']
  template_name = 'blogwapp/blog/create.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['project_id'] = self.kwargs.get('pk')
    return context 

  def form_valid(self, form):
    pk = self.kwargs.get("pk", None)
    form.instance.project_id = pk
    return super(BlogCreateView, self).form_valid(form)  

class BlogUpdateView(generic.UpdateView,LoginRequiredMixin):
  model = Blog
  fields = ['text']
  template_name = 'blogwapp/blog/update.html'

class BlogDeleteView(generic.DeleteView,LoginRequiredMixin):
  pass

class JSONResponseMixin:
    """
    A mixin that can be used to render a JSON response.
    """
    def render_to_json_response(self, context, **response_kwargs):
        """
        Returns a JSON response, transforming 'context' to make the payload.
        """
        return JsonResponse(
            self.get_data(context),
            **response_kwargs
        )

    def get_data(self, context):
        """
        Returns an object that will be serialized as JSON by json.dumps().
        """
        # Note: This is *EXTREMELY* naive; in reality, you'll need
        # to do much more complex handling to ensure that arbitrary
        # objects -- such as Django model instances or querysets
        # -- can be serialized as JSON.
        return context


class JSONView(JSONResponseMixin, TemplateView):
    def render_to_response(self, context, **response_kwargs):
        return self.render_to_json_response(context, **response_kwargs)

"""class ProjectListView(View):

  def get(self, request, *args, **kwargs):
        " ""Return the last five published questions." ""
        return toJson(Project.objects.order_by('-creat_date')[:5])
"""

def toJson(context):
  #print('context',context)
  info = serializers.serialize('json',context,fields=('id','name'))
  #return JsonResponse(info,safe=False)
  return HttpResponse(info, content_type="application/json")

blogw/blogwapp/templates/blogwapp/blog/create.html
{% include './generic_form.html' with action="Create"  %}

blogw/blogwapp/templates/blogwapp/blog/detail.html
{%extends 'base.html' %}

{%block content %}

<h1>Blog Detail</h1>

<div class="bg-light bg-gradient">
  <div class="row p-2 border">
    <div class="col">
      Date
    </div>
    <div class="col">
      {{ object.creat_date }}
    </div>
  </div>

  <div class="row p-2 border">
    <div class="col">
      Text
    </div>
    <div class="col">
      {{ object.text }}
    </div>
  </div>
</div>

<div class="row py-2">
  <div class="col">
    <a href="{% url 'blogwapp:blog-list' object.project_id %}">Blogs</a>
  </div>
  <div class="col">
    <a href="{% url 'blogwapp:project-list' %}">Projects</a>
  </div>
</div>
{%endblock %}

blogw/blogwapp/templates/blogwapp/blog/generic_form.html
{%extends 'base.html' %}

{%block content %}

<h1>{{ action }} Blog</h1>
<div class="row">
  <form method="post">
    <div class="mb-3">
      <label for="name" class="form-label">Text</label>
      {% include '../field_snippet.html' with field=form.text %}
      <input type="text" name="text" class="form-control" placeholder="write text" value="{{form.text.value|default:''}}" required>
    </div>
    <input type="hidden" name="project_id" value="{{project_id}}">
    <input type="submit" value="Submit" class="btn btn-success">
    {% csrf_token %}
  </form>
</div>


{%endblock %}

blogw/blogwapp/templates/blogwapp/blog/list.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
<div class="row align-justify-between">
  <div class="col-10">
    <h1>List Blogs</h1>
  </div>

  <div class="col text-end">
     <a href="{% url 'blogwapp:blog-add' project_id %}" id="link_block_blog_create"> 
      <i class="bi-plus-circle-fill" style="font-size: 2rem; color:chartreuse"  title="New Blog"></i>
    </a>
  </div>
</div>

<div class="col">
  <form action="{% url 'projectapi:blog-list' %}" id="search_blog" class="row gy-2 gx-2 align-items-center">
    <div class="col-10">
      <div class="input-group">
      <input class="form-control" type="search" name="text" placeholder="search in blogs" aria-label="text" aria-describedby="text">
      <input type="hidden" name="project_id" value="{{project_id}}">
      <button class="btn btn-outline-secondary" type="button" id="link_clear_search_blog" title="clear search">
        <i class="bi bi-x-circle-fill"></i>  
      </button>
      </div> 
    </div>  

    <div class="col-2">
      <button type="button" class="btn btn-success" id="link_search_blog">Search</button>
    </div>  
      <input type="hidden" name="project_id" value="" class="{{ project_id }}">
  </form>
</div>

<a class="hidden" id="url_blogs" href="{% url 'projectapi:blog-list' %}?project_id={{project_id}}"></a>
<div class="list-group list-group-flush" id="tgt_blog_list">
</div>

  <script src="{% static 'blogwapp/js/mustache.js' %}" crossorigin="anonymous"></script>
  <script src="{% static 'blogwapp/js/model.js' %}" crossorigin="anonymous"></script>
  <script src="{% static 'blogwapp/js/projectc.js' %}" crossorigin="anonymous"></script>
  <script src="{% static 'blogwapp/js/blogc.js' %}" crossorigin="anonymous"></script>
  <script src="{% static 'blogwapp/js/main.js' %}" ></script>
<script src="{% static 'blogwapp/js/blogload.js' %}"></script>
{% include "../templatemst.html" %}
{% endblock %}

blogw/blogwapp/templates/blogwapp/blog/update.html
{% include './generic_form.html' with action="Update"  %}